name: "Bug report 🐛"
description: Report errors or unexpected behavior
labels: ["Needs-Triage "]
body:
  - type: markdown
    attributes:
        value: |
          > **Important: When reporting bug or security issues, DO NOT attach any critical information like secret keys**.
          >
          > Please use this form and describe your issue, concisely but precisely, with as much detail as possible.
  - type: textarea
    attributes:
      label: Brief description of your issue
      placeholder: Briefly describe your issue here.
    validations:
      required: true
  - type: textarea
    attributes:
      label: Steps to reproduce
      placeholder: A description of how to trigger this bug
    validations:
      required: true
  - type: textarea
    attributes:
      label: Expected behavior
      placeholder: What did you expect to happen?
    validations:
      required: true
  - type: textarea
    attributes:
      label: Actual behavior
      placeholder: What is currently happening?
    validations:
      required: true
  - type: textarea
    attributes:
      label: Environment
      placeholder: |
        [dotnet --info]
        [dotnet ef --version]

        Any other software?
      render: shell
    validations:
      required: true
  - type: dropdown
    id: browsers
    attributes:
      label: What browsers are you seeing the problem on?
      multiple: true
      options:
        - Firefox
        - Chrome
        - Safari
        - Microsoft Edge