name: "🌐 Localization/Translation issue"
description: Report incorrect translations.
labels:
- Area-Localization
- Issue-Translation
- Needs-Triage
body:
- type: markdown
  attributes:
    value: Please make sure to [search for existing issues](https://github.com/SOFTINUX/Base/issues) before filing a new one!
- type: input
  attributes:
    label: 🌐 Language affected
    placeholder: "French"
  validations:
    required: true
- type: textarea
  attributes:
    label: ❌ Actual phrase(s)
    placeholder: What is there? Please include a screenshot as that is extremely helpful.
  validations:
    required: true
- type: textarea
  attributes:
    label: ✔️ Expected phrase(s)
    placeholder: What was expected?
  validations:
    required: true
- type: textarea
  attributes:
    label: ℹ Why is the current translation wrong
    placeholder: Why do you feel this is incorrect?
  validations:
    required: true